### ISSUE TITLE
find_code function

### ISSUE THREAD

**Issue by HunterOfGalaxy** [Numerlor/renpy-gallery-inject#1]
Hey! can you give an example how to use find_code in gallery

I have this code and I don't know what's wrong

with suppress(Exception):
        start_node=find_code(find_label("start"), {start_var}, return_previous=True)
        end_node=find_code(ANY_LABEL, {end_var}, return_previous=True)
        patch_after_node(end_node, create_end_replay_node())
        create_artificial_label(start_node, 'replay1')

**Comment by Numerlor** [comment]
the expected variables set expects strings of the variables or values of constats used in the function, e.g. for

```rpy
label start:
    python:
        some_variable = 545
        another_variable.attribute
        len("stringy")
```

you can do
```pycon
>>> find_code(find_label("start"), {"len"})
<renpy.ast.Python object at 0x0000000004ddc3a0>
>>> find_code(find_label("start"), {"some_variable"})
<renpy.ast.Python object at 0x0000000004ddc3a0>
>>> find_code(find_label("start"), {545})
<renpy.ast.Python object at 0x0000000004ddc3a0>
>>> find_code(find_label("start"), {"attribute"})
<renpy.ast.Python object at 0x0000000004ddc3a0>
>>> find_code(find_label("start"), {"invalid var"})
None
```
If any of them is in the set passed to `find_code` it'll match the node. (Maybe making sure the lookup set is a subset of the function's set would make more sense to be able to narrow things down?)

You can get the set of values that'll match by doing `code.co_varnames + code.co_names + code.co_consts` on the bytecode, either with the RenPy Python object, or pasting it as a function directly in Python.
```pycon

In [1]: def function():
   ...:     some_variable = 545
   ...:     another_variable.attribute
   ...:     len("stringy")
   ...:

In [2]: code = function.__code__

In [3]: code.co_varnames + code.co_names + code.co_consts
Out[3]: ('some_variable', 'another_variable', 'attribute', 'len', None, 545, 'stringy')
```

Thinking about it a generic lookup function that'd just match the passed in node would also be useful, but in this case if you know that the next `Python` node is going to be the right one you should be able to do the lookup with `{None}` as that constant will always be present implicitly.

**Comment by HunterOfGalaxy** [comment]
Ok, thanks I got it. And what is the use of ANY_LABEL as I posted earlier.

**Comment by Numerlor** [comment]
> Ok, thanks I got it. And what is the use of ANY_LABEL as I posted earlier.

it'll try to look for the node in all the defined labels instead of just going through a single one, though that can be a fair bit slower and I don't think it checks for nested labels

**Comment by HunterOfGalaxy** [comment]
Here is something I wanna ask:
I used end_code= find_code(ANY_LABEL, {'end_preview'})
and I wanted to end the replay based on the choices in label start but when
I chose choice 2 replay didn't end in label 2 instead of it continued to
end3

Note:* I know find_code is checking for the first node when it's searching
for the
end_preview variable.
*Is there any way to solve this?



label start:

     e "blah blah blah blah......"
     menu:
               "Choice 1":
                             $var=True
                "Choice 2":
                             $var=False
       if var==True:
                  jump end1
       else:
                  jump end2
label end1:
'Replay1 Ended'
$end_preview =True
'Ending reached'

return

label end2:
'Replay2 Ended'
$end_preview = True
'Ending reached'
jump end3

**Comment by Numerlor** [comment]
You'll need to find it from both of the labels as they're completely separate nodes, so ideally looking up both end1 and end2 labels as the start nodes and finding the Python node with end_preview from there (or going off of some other node like Say).

If that's not viable and you have to search for it globally, you'll probably have to change the finding code in ast_utils. For example by copying the current `find_code` and adding some exclusion mechanism to not match the previously found nodes in the predicate. Or changing the underlying function to be a generator for all matching nodes but that'd be more involved

Also just so it's clear, in case you have control of the game's script, you should just add things normally there instead of using this for patching it.

**Comment by HunterOfGalaxy** [comment]
Thanks for the tip!

I'll add some mechanism to achieve it.
